In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [4]:
print(x)
print(y)
#The array x is required to be two-dimensional.
#It should have one column for each input, and the number of rows should be equal to the number of observations.
#It contains only zeros and ones since this is a binary classification problem.

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 0 0 0 1 1 1 1 1 1]


# Create a Model and Train It

In [6]:
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

#solver is a string ('liblinear' by default) that decides what solver to use for fitting the model.
#random_state is an integer, an instance of numpy.RandomState, or None (default) that defines what pseudo-random number generator to use.

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

# what does every parameter mean?

penalty is a string ('l2' by default) that decides whether there is regularization and which approach to use. Other options are 'l1', 'elasticnet', and 'none'.

dual is a Boolean (False by default) that decides whether to use primal (when False) or dual formulation (when True).

tol is a floating-point number (0.0001 by default) that defines the tolerance for stopping the procedure.

C is a positive floating-point number (1.0 by default) that defines the relative strength of regularization. Smaller values indicate stronger regularization.

fit_intercept is a Boolean (True by default) that decides whether to calculate the intercept 𝑏₀ (when True) or consider it equal to zero (when False).

intercept_scaling is a floating-point number (1.0 by default) that defines the scaling of the intercept 𝑏₀.

class_weight is a dictionary, 'balanced', or None (default) that defines the weights related to each class. When None, all classes have the weight one.

random_state is an integer, an instance of numpy.RandomState, or None (default) that defines what pseudo-random number generator to use.

solver is a string ('liblinear' by default) that decides what solver to use for fitting the model. Other options are 'newton-cg', 'lbfgs', 'sag', and 'saga'.

max_iter is an integer (100 by default) that defines the maximum number of iterations by the solver during model fitting.

multi_class is a string ('ovr' by default) that decides the approach to use for handling multiple classes. Other options are 'multinomial' and 'auto'.

verbose is a non-negative integer (0 by default) that defines the verbosity for the 'liblinear' and 'lbfgs' solvers.

warm_start is a Boolean (False by default) that decides whether to reuse the previously obtained solution.

n_jobs is an integer or None (default) that defines the number of parallel processes to use. None usually means to use one core, while -1 means to use all available cores.

l1_ratio is either a floating-point number between zero and one or None (default). It defines the relative importance of the L1 part in the elastic-net regularization.

In [7]:
model.classes_

array([0, 1])

# to get the value of the slope 𝑏₁ and the intercept 𝑏₀ of the linear function 𝑓

In [11]:
print(model.intercept_)
print(model.coef_)

[-1.04608067]
[[0.51491375]]


#  Evaluate the Model

In [13]:
model.predict_proba(x)
#returns the matrix of probabilities that the predicted output is equal to zero or one

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

# In the matrix above, each row corresponds to a single observation. The first column is the probability of the predicted output being zero, that is 1 - 𝑝(𝑥). The second column is the probability that the output is one, or 𝑝(𝑥).

In [14]:
# to  get the actual predictions, based on the probability matrix
model.predict(x)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [15]:
model.score(x, y)
#.score() takes the input and output as arguments and returns the ratio of the number of correct predictions to the number of observations.

0.9

 to calculate confusion matrix

In [17]:
confusion_matrix(y, model.predict(x))

array([[3, 1],
       [0, 6]], dtype=int64)

In [18]:
print(classification_report(y, model.predict(x)))

             precision    recall  f1-score   support

          0       1.00      0.75      0.86         4
          1       0.86      1.00      0.92         6

avg / total       0.91      0.90      0.90        10

